
public class Data {
String s = "/9j/4QgFRXhpZgAATU0AKgAAAAgACQEPAAIAAAAIAAAAegEQAAIAAAAIAAAAggEaAAUAAAABAAAA\r\n" + 
		"    igEbAAUAAAABAAAAkgEoAAMAAAABAAIAAAEyAAIAAAAUAAAAmgITAAMAAAABAAEAAIdpAAQAAAAB\r\n" + 
		"    AAAAroglAAQAAAABAAACkgAAAuhRQ09NLUFBAFFDQU0tQUEAAAAASAAAAAEAAABIAAAAATIwMTk6\r\n" + 
		"    MDg6MDYgMTE6MzI6NTYAAByCmgAFAAAAAQAAAgSCnQAFAAAAAQAAAgyIIgADAAAAAQAAAACIJwAD\r\n" + 
		"    AAAAAQMgAACQAAAHAAAABDAyMjCQAwACAAAAFAAAAhSQBAACAAAAFAAAAiiRAQAHAAAABAECAwCS\r\n" + 
		"    AQAKAAAAAQAAAjySAgAFAAAAAQAAAkSSAwAKAAAAAQAAAkySBwADAAAAAQABAACSCQADAAAAAQAQ\r\n" + 
		"    AACSCgAFAAAAAQAAAlSSkAACAAAABwAAAlySkQACAAAABwAAAmSSkgACAAAABwAAAmygAAAHAAAA\r\n" + 
		"    BDAxMDCgAQADAAAAAQABAACgAgAEAAAAAQAADwCgAwAEAAAAAQAACHCgBQAEAAAAAQAAAnOiFwAD\r\n" + 
		"    AAAAAQACAACjAQAHAAAAAQEAAACkAgADAAAAAQAAAACkAwADAAAAAQAAAACkBQADAAAAAQAAAACk\r\n" + 
		"    BgADAAAAAQAAAAAAAAAAAAAAAQAAAAgAAADIAAAAZDIwMTk6MDg6MDYgMTE6MzI6NTYAMjAxOTow\r\n" + 
		"    ODowNiAxMTozMjo1NgAAAAt/AAAD6AAAAMgAAABkAAAAAAAAAGQAAAFwAAAAZDk4MzEwMQAAOTgz\r\n" + 
		"    MTAxAAA5ODMxMDEAAAIAAQACAAAABFI5OAAAAgAHAAAABDAxMDAAAAAAAAADAAUABQAAAAEAAAK8\r\n" + 
		"    AAcABQAAAAMAAALEAB0AAgAAAAsAAALcAAAAAAAAAMgAAABkAAAAAwAAAAEAAAAgAAAAAQAAADgA\r\n" + 
		"    AAABMjAxOTowODowNgAAAAYBAwADAAAAAQAGAAABGgAFAAAAAQAAAzYBGwAFAAAAAQAAAz4BKAAD\r\n" + 
		"    AAAAAQACAAACAQAEAAAAAQAAA0YCAgAEAAAAAQAABLcAAAAAAAAASAAAAAEAAABIAAAAAf/Y/9sA\r\n" + 
		"    hAAIBgYHBgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMcHCg3KSwwMTQ0NB8n\r\n" + 
		"    OT04MjwuMzQyAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy\r\n" + 
		"    MjIyMjIyMjIyMjIyMjIyMjL/wAARCACQAQADASIAAhEBAxEB/8QBogAAAQUBAQEBAQEAAAAAAAAA\r\n" + 
		"    AAECAwQFBgcICQoLEAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHB\r\n" + 
		"    FVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2\r\n" + 
		"    d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna\r\n" + 
		"    4eLj5OXm5+jp6vHy8/T19vf4+foBAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKCxEAAgECBAQD\r\n" + 
		"    BAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRom\r\n" + 
		"    JygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaX\r\n" + 
		"    mJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6\r\n" + 
		"    /90ABAAQ/9oADAMBAAIRAxEAPwDwGiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA\r\n" + 
		"    CiiigAooooAKKKKACiiigAooooAKKKKACiiigD//0PAaKKKACiiigAooooAKKKKACiiigAooooAK\r\n" + 
		"    KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//R8BopaSgAooooAKKKKACi\r\n" + 
		"    iigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD/9LwGiii\r\n" + 
		"    gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA\r\n" + 
		"    CiiigD//0/AqSiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAC\r\n" + 
		"    iiigAooooAKKKKACiiigD//U8CpKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKK\r\n" + 
		"    KKACiiigAooooAKKKKACiiigAooooAKKKKAP/9XwGiiigAooooAKKKKACiiigAooooAKKKKACiii\r\n" + 
		"    gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//1vAaKWkoAKKKKACiiigAoooo\r\n" + 
		"    AKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//X8BooooAK\r\n" + 
		"    KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo\r\n" + 
		"    ooA//9n/2wCEAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsI\r\n" + 
		"    CQoKCgoKBggLDAsKDAkKCgoBAgICAgICBQMDBQoHBgcKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoK\r\n" + 
		"    CgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCv/AABEICHAPAAMBIgACEQEDEQH/xAGiAAABBQEBAQEB\r\n" + 
		"    AQAAAAAAAAAAAQIDBAUGBwgJCgsQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQy\r\n" + 
		"    gZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVm\r\n" + 
		"    Z2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS\r\n" + 
		"    09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+gEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL\r\n" + 
		"    EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ0\r\n" + 
		"    4SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeI\r\n" + 
		"    iYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery\r\n" + 
		"    8/T19vf4+fr/2gAMAwEAAhEDEQA/APwPmcRyP/eK4NVl3sWA6E81NdIRIZOuT3qJJWU4AAHfigBW\r\n" + 
		"    ijC4Bye+DTYZAuAR1PJFLIRwE6nriiNAM71JI684oAljSJmO8nBHBzUZJViSRuHTJok+UZUnBPTN\r\n" + 
		"    IshCluCM9CKAGuzdWXqeTS70CjAAPcAVIiiRDI5BC8kZxUPAbOOO4oAcqb+/NKyAP1Ptml39GQYJ\r\n" + 
		"    POBzScltzZJNABLkjAzgn0pBsKfMCSPSpE2txIDk9CBUtnp01xcLBGoJdgAMUAVQO3b1xSqW3lQD\r\n" + 
		"    nPIIzUs8RSRkCjj0qNHKS5K89uKAJIozGTnGT1HbrUoIIKjAyDkA9KgkcE5xye1KpKPmTjjgHtQA\r\n" + 
		"    OgXIGd3b2pm4gkEHkc4p0koOSoNNOJDgDkdM0ACoXIUAnaOBinsikjaOccgU1N0QG0EEdeaeZ48A\r\n" + 
		"    kYYjBOaAGt5QXG0Ekc1EAQWCnjuKkYqDvDAEmkiKq+9+cHkZ";
}
